In [46]:
import numpy as np

mylist = [1,2,3,4]

#converting to numpy array
np.array(mylist)

array([1, 2, 3, 4])

In [2]:
mylist

[1, 2, 3, 4]

In [3]:
type(mylist)

list

In [4]:
arr = np.array(mylist)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
#built in functions in Numpy that allows to quickly create some arrays
#one of most common arange(start,stop,step)

a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
type(1.0)

float

In [14]:
type(1.)

float

In [15]:
type(1)

int

In [16]:
np.random.randint(0,100)

35

In [17]:
np.random.randint(0,100)

19

In [18]:
np.random.randint(0,100)

53

In [20]:
np.random.randint(0,100,(5,5))

array([[16, 54, 13, 10, 79],
       [99, 35, 78, 51, 34],
       [94, 43, 68, 49, 52],
       [79, 57, 67, 74, 18],
       [91, 88,  0, 33, 72]])

In [21]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [22]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [23]:
np.linspace(0,10,200)

array([ 0.        ,  0.05025126,  0.10050251,  0.15075377,  0.20100503,
        0.25125628,  0.30150754,  0.35175879,  0.40201005,  0.45226131,
        0.50251256,  0.55276382,  0.60301508,  0.65326633,  0.70351759,
        0.75376884,  0.8040201 ,  0.85427136,  0.90452261,  0.95477387,
        1.00502513,  1.05527638,  1.10552764,  1.15577889,  1.20603015,
        1.25628141,  1.30653266,  1.35678392,  1.40703518,  1.45728643,
        1.50753769,  1.55778894,  1.6080402 ,  1.65829146,  1.70854271,
        1.75879397,  1.80904523,  1.85929648,  1.90954774,  1.95979899,
        2.01005025,  2.06030151,  2.11055276,  2.16080402,  2.21105528,
        2.26130653,  2.31155779,  2.36180905,  2.4120603 ,  2.46231156,
        2.51256281,  2.56281407,  2.61306533,  2.66331658,  2.71356784,
        2.7638191 ,  2.81407035,  2.86432161,  2.91457286,  2.96482412,
        3.01507538,  3.06532663,  3.11557789,  3.16582915,  3.2160804 ,
        3.26633166,  3.31658291,  3.36683417,  3.41708543,  3.46

In [24]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [25]:
np.random.randint(0,100,10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [26]:
arr = np.random.randint(0,100,10)

In [27]:
arr

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [28]:
arr.max()

83

In [29]:
arr.min()

8

In [30]:
arr.min

<function ndarray.min>

In [31]:
arr.min()

8

In [32]:
arr.mean()

40.7

In [33]:
arr.argmax()

1

In [34]:
arr.argmin()

2

In [35]:
arr.reshape(2,5)

array([[49, 83,  8, 29, 59],
       [34, 44, 72, 19, 10]])

In [36]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
mat[5,2]

52

In [38]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [39]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [42]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
import pandas as pd 

In [55]:
df = pd.read_csv('salaries.csv')
print(df)

     Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27


In [56]:
print(df['Salary'])

0     50000
1    120000
2     80000
Name: Salary, dtype: int64


In [57]:
print(df[['Name','Salary']])

     Name  Salary
0    John   50000
1   Sally  120000
2  Alyssa   80000


In [62]:
print(df['Salary'].min())
print(df['Salary'].mean())

50000
83333.33333333333


In [63]:
print(df)

     Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27


In [67]:
ser_of_bool = df['Age'] > 30
print(ser_of_bool)

0     True
1     True
2    False
Name: Age, dtype: bool


In [68]:
print(df[df['Age'] > 30])

    Name  Salary  Age
0   John   50000   34
1  Sally  120000   45


In [69]:
print(df['Age'].unique())

[34 45 27]


In [72]:
print(df['Age'].nunique())

3


In [73]:
print(df.columns)

Index(['Name', 'Salary', 'Age'], dtype='object')


In [74]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Salary  3 non-null      int64 
 2   Age     3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes
None


In [75]:
print(df.describe())

              Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000


In [76]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)


In [87]:
mat = np.arange(0,10).reshape(5,2)
print(mat)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [88]:
df = pd.DataFrame(data=mat, columns=['A', 'B'])
print(df)

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
