In [2]:
import numpy as np
import pandas as pd

In [7]:
np.random.seed(101)

In [10]:
mat = np.random.randint(1,101,(100,5))
print(mat)

[[ 16  96  92  20  70]
 [  2  78  64  88  29]
 [ 71   6   4  13  63]
 [ 27  97  62  88  75]
 [100  98  65  96   4]
 [ 89  60  39  30  32]
 [ 89  58  10  63  32]
 [ 14  36  48   3  18]
 [ 51  23  31  37  23]
 [ 98  52  39  29   5]
 [  1  13  91   3   8]
 [ 45  55  50  77  99]
 [  4  33  92  44   8]
 [ 43  67  10   6  27]
 [ 67  23  48  28  47]
 [ 15  53  75  55   4]
 [ 95  37  64  42  19]
 [ 38  46  83  48  67]
 [ 98  21  10  88  41]
 [ 14  96  17  39  88]
 [ 73  61  79  54  49]
 [ 84  91  42  85  79]
 [ 56  71  94  58  87]
 [ 68   9  48  71  40]
 [ 54   6  41  89  59]
 [ 13  71   6  83   9]
 [ 61  59  46  93  86]
 [ 45  63  40  39  55]
 [ 99  81  94  17  38]
 [ 59  41  73  73  23]
 [ 43  39  46  17  53]
 [ 18  23  16  19  38]
 [ 49   3   3  32  51]
 [ 79  71  41  61  63]
 [ 70  35  96  59   5]
 [ 71  21  19  67  24]
 [ 88  46  65   7  40]
 [ 30  61  34  19  60]
 [ 65  60  66  11  87]
 [ 67  39  77  98  80]
 [  8  66  51  54   5]
 [ 40   2   6  68  93]
 [ 51  60   3  92  15]
 [ 13  69  

In [12]:
df = pd.DataFrame(mat)
print(df)

      0   1   2   3   4
0    16  96  92  20  70
1     2  78  64  88  29
2    71   6   4  13  63
3    27  97  62  88  75
4   100  98  65  96   4
..  ...  ..  ..  ..  ..
95   11  49  87  34  53
96   25  95  79  72  20
97   76  82  72  24  94
98   59  49  77  64  59
99   29  85  48  41  64

[100 rows x 5 columns]


In [14]:
df.columns = ['f1','f2','f3','f4','label']
print(df)

     f1  f2  f3  f4  label
0    16  96  92  20     70
1     2  78  64  88     29
2    71   6   4  13     63
3    27  97  62  88     75
4   100  98  65  96      4
..  ...  ..  ..  ..    ...
95   11  49  87  34     53
96   25  95  79  72     20
97   76  82  72  24     94
98   59  49  77  64     59
99   29  85  48  41     64

[100 rows x 5 columns]


In [33]:
#TASK

random_numbers = np.random.randint(1,100,200)
print(random_numbers)

[46 77 30 85 14 43 24 39 77 17 32 92 27 11 89 37 68 31  7 57 21 93 71  3
 81 20 86 69 64 54 78 44 83 87 38 39 51 92 77 17 18 81 95 58  3 95 22 92
 99 12  3 83  3 83 88 99 58 52 78 26 38 34 16 34  5 81 74 40 55  7  2 22
 80 20 10 33 93 90 16 83  5 76 65  4 90 14 41 10 18 28 60 16 37 30 88 82
 42 88 95 97 12 34 94 81 49  5 49 50 46 44 84 22 28 64 14 22 41 55 32 82
 44 64 54 48 52 92 60 14 61 47  4 36 91 69 59 44 20 18 28 78 35 21 10 31
 41 60 89 93 91 27 73 40 46 24 38 41 11 12 85 24  7 25 19 38 25 81 25 26
  6 68 99 79 31 37 53 17 72 85 28 40 21 46 20 15 23 98 68 77 74 86 60 39
 72 13 78  3  7 39 25 28]


In [34]:
random_mat = random_numbers.reshape(50,4)
print(random_mat)

[[46 77 30 85]
 [14 43 24 39]
 [77 17 32 92]
 [27 11 89 37]
 [68 31  7 57]
 [21 93 71  3]
 [81 20 86 69]
 [64 54 78 44]
 [83 87 38 39]
 [51 92 77 17]
 [18 81 95 58]
 [ 3 95 22 92]
 [99 12  3 83]
 [ 3 83 88 99]
 [58 52 78 26]
 [38 34 16 34]
 [ 5 81 74 40]
 [55  7  2 22]
 [80 20 10 33]
 [93 90 16 83]
 [ 5 76 65  4]
 [90 14 41 10]
 [18 28 60 16]
 [37 30 88 82]
 [42 88 95 97]
 [12 34 94 81]
 [49  5 49 50]
 [46 44 84 22]
 [28 64 14 22]
 [41 55 32 82]
 [44 64 54 48]
 [52 92 60 14]
 [61 47  4 36]
 [91 69 59 44]
 [20 18 28 78]
 [35 21 10 31]
 [41 60 89 93]
 [91 27 73 40]
 [46 24 38 41]
 [11 12 85 24]
 [ 7 25 19 38]
 [25 81 25 26]
 [ 6 68 99 79]
 [31 37 53 17]
 [72 85 28 40]
 [21 46 20 15]
 [23 98 68 77]
 [74 86 60 39]
 [72 13 78  3]
 [ 7 39 25 28]]


In [35]:
col_names = 'A B C D'.split()
print(col_names)

['A', 'B', 'C', 'D']


In [37]:
df = pd.DataFrame(data = random_mat,columns=col_names)
print(df)

     A   B   C   D
0   46  77  30  85
1   14  43  24  39
2   77  17  32  92
3   27  11  89  37
4   68  31   7  57
5   21  93  71   3
6   81  20  86  69
7   64  54  78  44
8   83  87  38  39
9   51  92  77  17
10  18  81  95  58
11   3  95  22  92
12  99  12   3  83
13   3  83  88  99
14  58  52  78  26
15  38  34  16  34
16   5  81  74  40
17  55   7   2  22
18  80  20  10  33
19  93  90  16  83
20   5  76  65   4
21  90  14  41  10
22  18  28  60  16
23  37  30  88  82
24  42  88  95  97
25  12  34  94  81
26  49   5  49  50
27  46  44  84  22
28  28  64  14  22
29  41  55  32  82
30  44  64  54  48
31  52  92  60  14
32  61  47   4  36
33  91  69  59  44
34  20  18  28  78
35  35  21  10  31
36  41  60  89  93
37  91  27  73  40
38  46  24  38  41
39  11  12  85  24
40   7  25  19  38
41  25  81  25  26
42   6  68  99  79
43  31  37  53  17
44  72  85  28  40
45  21  46  20  15
46  23  98  68  77
47  74  86  60  39
48  72  13  78   3
49   7  39  25  28
